// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('alMakinah').config(function($logProvider, $authProvider) {
    'ngInject';

    $logProvider.debugEnabled(true);
    $authProvider.configure([{
      mentor: {
        apiUrl: 'http://localhost:3000/mentor',
      }
    }, {
      student: {
        apiUrl: 'http://localhost:3000/student',
      }
    }, {
      manager: {
        apiUrl: 'http://localhost:3000/manager',
      }
    }]
  );
  });

}).call(this);
