// Generated by CoffeeScript 1.10.0
(function() {
  angular.
    module('alMakinah', [
        'ngAnimate',
        'ngCookies',
        'ngSanitize',
        'ngStorage',
        'ui.router',
        'ui.bootstrap',
        'toaster',
        'ng-token-auth',
        'ui.router',
        'hm.readmore',
        'yaru22.angular-timeago',
        'angularMoment',
        'chart.js',
        'ngFileUpload',
        'ngActionCable',
        'chart.js',
        'myApp.config'
    ]);

}).call(this);
