// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('alMakinah').run(function($log, $rootScope, actionCable) {
    'ngInject';

    $rootScope.actionCable = actionCable;
    
    return $log.debug('runBlock end');
  });

}).call(this);
